"""Add plan and plan_renewal columns to user table

Revision ID: dc21d8ef4eb9
Revises: 
Create Date: 2025-05-07 22:42:06.315684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc21d8ef4eb9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plan', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('plan_renewal', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('plan_renewal')
        batch_op.drop_column('plan')

    # ### end Alembic commands ###
